import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/components/Header/Header';

import './scss/globals.scss';
import { AppWrapper } from '@/context';

const inter = Inter({
	subsets: ['cyrillic', 'latin'],
	weight: ['300', '400', '500', '600', '700']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={inter.className}>
				<Header />
				<main>
					<AppWrapper>{children}</AppWrapper>
				</main>
			</body>
		</html>
	);
}
